"""Deterministic SQL generator (PostgreSQL by default).

Produces a ``SqlArtifact`` containing a CREATE-statement block and,
optionally, an Alembic revision script for the same model.
"""

from __future__ import annotations

from datetime import datetime, timezone
from textwrap import dedent

from backend.domain.exceptions import SqlGenerationError
from backend.domain.models.artifacts import (
    MigrationPlan,
    MigrationStep,
    SqlArtifact,
)
from backend.domain.models.ir import (
    RelationalAttribute,
    RelationalModel,
    RelationalRelationship,
    RelationalTable,
)


def _quote(identifier: str) -> str:
    return f'"{identifier}"'


def _column_clause(attr: RelationalAttribute) -> str:
    parts: list[str] = [_quote(attr.name), attr.sql_type]
    if not attr.nullable:
        parts.append("NOT NULL")
    if attr.default is not None:
        parts.append(f"DEFAULT {attr.default}")
    if attr.is_unique:
        parts.append("UNIQUE")
    return " ".join(parts)


def _primary_key_clause(table: RelationalTable) -> str | None:
    pk_cols = table.primary_key or [a.name for a in table.attributes if a.is_primary_key]
    if not pk_cols:
        return None
    cols = ", ".join(_quote(c) for c in pk_cols)
    return f"PRIMARY KEY ({cols})"


def _create_table_sql(table: RelationalTable) -> str:
    if not table.attributes:
        raise SqlGenerationError(f"Table '{table.name}' has no attributes")

    column_lines = [f"    {_column_clause(a)}" for a in table.attributes]
    pk_clause = _primary_key_clause(table)
    if pk_clause:
        column_lines.append(f"    {pk_clause}")

    body = ",\n".join(column_lines)
    stmt = f"CREATE TABLE {_quote(table.name)} (\n{body}\n);"

    if table.description:
        stmt += f"\nCOMMENT ON TABLE {_quote(table.name)} IS '{_escape(table.description)}';"
    for attr in table.attributes:
        if attr.description:
            stmt += (
                f"\nCOMMENT ON COLUMN {_quote(table.name)}.{_quote(attr.name)} "
                f"IS '{_escape(attr.description)}';"
            )
    return stmt


def _create_index_sql(table: RelationalTable) -> list[str]:
    statements: list[str] = []
    for idx in table.indexes:
        unique = "UNIQUE " if idx.unique else ""
        cols = ", ".join(_quote(c) for c in idx.columns)
        statements.append(
            f"CREATE {unique}INDEX {_quote(idx.name)} ON {_quote(table.name)} ({cols});"
        )
    return statements


def _foreign_key_sql(rel: RelationalRelationship) -> str:
    src_cols = ", ".join(_quote(c) for c in rel.source_columns)
    tgt_cols = ", ".join(_quote(c) for c in rel.target_columns)
    on_delete = f" ON DELETE {rel.on_delete}" if rel.on_delete else ""
    on_update = f" ON UPDATE {rel.on_update}" if rel.on_update else ""
    return (
        f"ALTER TABLE {_quote(rel.source_table)} "
        f"ADD CONSTRAINT {_quote(rel.name)} "
        f"FOREIGN KEY ({src_cols}) REFERENCES {_quote(rel.target_table)} ({tgt_cols})"
        f"{on_delete}{on_update};"
    )


def _escape(value: str) -> str:
    return value.replace("'", "''")


class SqlGenerator:
    """Generate deterministic SQL DDL from a ``RelationalModel``."""

    def generate(
        self,
        model: RelationalModel,
        *,
        emit_alembic: bool = False,
    ) -> tuple[SqlArtifact, MigrationPlan]:
        if not model.tables:
            raise SqlGenerationError("Cannot generate SQL from an empty relational model")

        steps: list[MigrationStep] = []
        order = 0

        ddl_parts: list[str] = [
            "-- Generated by db_gerador. Dialect: PostgreSQL.",
            f"-- Generated at: {datetime.now(tz=timezone.utc).isoformat()}",
            "",
        ]

        for table in model.tables:
            order += 1
            sql = _create_table_sql(table)
            ddl_parts.append(sql)
            ddl_parts.append("")
            steps.append(
                MigrationStep(
                    order=order, operation="create_table", target=table.name, sql=sql
                )
            )

            for idx_sql in _create_index_sql(table):
                order += 1
                ddl_parts.append(idx_sql)
                steps.append(
                    MigrationStep(
                        order=order,
                        operation="create_index",
                        target=table.name,
                        sql=idx_sql,
                    )
                )
            ddl_parts.append("")

        for rel in model.relationships:
            order += 1
            fk_sql = _foreign_key_sql(rel)
            ddl_parts.append(fk_sql)
            steps.append(
                MigrationStep(
                    order=order,
                    operation="add_foreign_key",
                    target=rel.source_table,
                    sql=fk_sql,
                )
            )

        ddl = "\n".join(ddl_parts).rstrip() + "\n"
        alembic_script = self._render_alembic(model) if emit_alembic else None

        artifact = SqlArtifact(
            dialect="postgresql",
            ddl=ddl,
            alembic_revision=alembic_script,
            summary=f"{len(model.tables)} tables, {len(model.relationships)} relationships",
        )
        plan = MigrationPlan(
            steps=steps,
            dialect="postgresql",
            summary=f"{len(steps)} migration steps",
        )
        return artifact, plan

    # ------------------------------------------------------------------
    # Alembic emitter (simple, op.execute-based for portability)
    # ------------------------------------------------------------------
    def _render_alembic(self, model: RelationalModel) -> str:
        revision_id = datetime.now(tz=timezone.utc).strftime("%Y%m%d%H%M%S")
        header = dedent(
            f'''
            """Auto-generated migration by db_gerador.

            Revision ID: {revision_id}
            """
            from alembic import op

            revision = "{revision_id}"
            down_revision = None
            branch_labels = None
            depends_on = None


            def upgrade() -> None:
            '''
        ).strip()

        body_lines: list[str] = []
        for table in model.tables:
            body_lines.append(f'    op.execute("""{_create_table_sql(table)}""")')
            for idx_sql in _create_index_sql(table):
                body_lines.append(f'    op.execute("""{idx_sql}""")')
        for rel in model.relationships:
            body_lines.append(f'    op.execute("""{_foreign_key_sql(rel)}""")')

        downgrade_lines: list[str] = []
        for rel in reversed(model.relationships):
            downgrade_lines.append(
                f'    op.execute("""ALTER TABLE {_quote(rel.source_table)} '
                f'DROP CONSTRAINT IF EXISTS {_quote(rel.name)};""")'
            )
        for table in reversed(model.tables):
            downgrade_lines.append(
                f'    op.execute("""DROP TABLE IF EXISTS {_quote(table.name)} CASCADE;""")'
            )

        return (
            f"{header}\n"
            + ("\n".join(body_lines) or "    pass")
            + "\n\n\ndef downgrade() -> None:\n"
            + ("\n".join(downgrade_lines) or "    pass")
            + "\n"
        )
